// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: helios.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取服务器信息请求
type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_helios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_helios_proto_rawDescGZIP(), []int{0}
}

// 获取服务器信息响应
type GetServerInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务器主机地址
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// 服务器端口
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// 内部标识头
	InternalFlag string `protobuf:"bytes,3,opt,name=internal_flag,json=internalFlag,proto3" json:"internal_flag,omitempty"`
	// 内部本地标识头
	InternalLocalFlag string `protobuf:"bytes,4,opt,name=internal_local_flag,json=internalLocalFlag,proto3" json:"internal_local_flag,omitempty"`
	// 内部后端标识头
	InternalBackendFlag string `protobuf:"bytes,5,opt,name=internal_backend_flag,json=internalBackendFlag,proto3" json:"internal_backend_flag,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_helios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_helios_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerInfoResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetServerInfoResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GetServerInfoResponse) GetInternalFlag() string {
	if x != nil {
		return x.InternalFlag
	}
	return ""
}

func (x *GetServerInfoResponse) GetInternalLocalFlag() string {
	if x != nil {
		return x.InternalLocalFlag
	}
	return ""
}

func (x *GetServerInfoResponse) GetInternalBackendFlag() string {
	if x != nil {
		return x.InternalBackendFlag
	}
	return ""
}

var File_helios_proto protoreflect.FileDescriptor

const file_helios_proto_rawDesc = "" +
	"\n" +
	"\fhelios.proto\x12\x04main\"\x16\n" +
	"\x14GetServerInfoRequest\"\xc8\x01\n" +
	"\x15GetServerInfoResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12#\n" +
	"\rinternal_flag\x18\x03 \x01(\tR\finternalFlag\x12.\n" +
	"\x13internal_local_flag\x18\x04 \x01(\tR\x11internalLocalFlag\x122\n" +
	"\x15internal_backend_flag\x18\x05 \x01(\tR\x13internalBackendFlag2Y\n" +
	"\rHeliosService\x12H\n" +
	"\rGetServerInfo\x12\x1a.main.GetServerInfoRequest\x1a\x1b.main.GetServerInfoResponseB\tZ\a./;mainb\x06proto3"

var (
	file_helios_proto_rawDescOnce sync.Once
	file_helios_proto_rawDescData []byte
)

func file_helios_proto_rawDescGZIP() []byte {
	file_helios_proto_rawDescOnce.Do(func() {
		file_helios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helios_proto_rawDesc), len(file_helios_proto_rawDesc)))
	})
	return file_helios_proto_rawDescData
}

var file_helios_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helios_proto_goTypes = []any{
	(*GetServerInfoRequest)(nil),  // 0: main.GetServerInfoRequest
	(*GetServerInfoResponse)(nil), // 1: main.GetServerInfoResponse
}
var file_helios_proto_depIdxs = []int32{
	0, // 0: main.HeliosService.GetServerInfo:input_type -> main.GetServerInfoRequest
	1, // 1: main.HeliosService.GetServerInfo:output_type -> main.GetServerInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helios_proto_init() }
func file_helios_proto_init() {
	if File_helios_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helios_proto_rawDesc), len(file_helios_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helios_proto_goTypes,
		DependencyIndexes: file_helios_proto_depIdxs,
		MessageInfos:      file_helios_proto_msgTypes,
	}.Build()
	File_helios_proto = out.File
	file_helios_proto_goTypes = nil
	file_helios_proto_depIdxs = nil
}
