// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: helios.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HeliosService_GetServerInfo_FullMethodName = "/main.HeliosService/GetServerInfo"
)

// HeliosServiceClient is the client API for HeliosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Helios服务定义
type HeliosServiceClient interface {
	// 获取服务器信息
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
}

type heliosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeliosServiceClient(cc grpc.ClientConnInterface) HeliosServiceClient {
	return &heliosServiceClient{cc}
}

func (c *heliosServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, HeliosService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeliosServiceServer is the server API for HeliosService service.
// All implementations must embed UnimplementedHeliosServiceServer
// for forward compatibility.
//
// Helios服务定义
type HeliosServiceServer interface {
	// 获取服务器信息
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	mustEmbedUnimplementedHeliosServiceServer()
}

// UnimplementedHeliosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeliosServiceServer struct{}

func (UnimplementedHeliosServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedHeliosServiceServer) mustEmbedUnimplementedHeliosServiceServer() {}
func (UnimplementedHeliosServiceServer) testEmbeddedByValue()                       {}

// UnsafeHeliosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeliosServiceServer will
// result in compilation errors.
type UnsafeHeliosServiceServer interface {
	mustEmbedUnimplementedHeliosServiceServer()
}

func RegisterHeliosServiceServer(s grpc.ServiceRegistrar, srv HeliosServiceServer) {
	// If the following call pancis, it indicates UnimplementedHeliosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HeliosService_ServiceDesc, srv)
}

func _HeliosService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeliosServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeliosService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeliosServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeliosService_ServiceDesc is the grpc.ServiceDesc for HeliosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeliosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.HeliosService",
	HandlerType: (*HeliosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerInfo",
			Handler:    _HeliosService_GetServerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helios.proto",
}
